### ISSUE TITLE
JSON 

### ISSUE THREAD

**Issue by Jip-Hop** [freethenation/durable-json-lint#1]
Hi,

I'm using a web-service that returns invalid JSON. While the durable-json-lint module is useful for fixing some errors, it currently doesn't fix unescaped unicode characters in the range of u0000 to u001f.

```
{"Title":"Symphony in Blood Red","Year":"2010","Rated":"N/A","Released":"21 Oct 2010","Runtime":"80 min","Genre":"Horror","Director":"Luigi Pastore","Writer":"Luigi Pastore (screenplay), Luigi Pastore (story), Antonio Tentori (screenplay)","Actors":"Sharon Alessandri, Nikol Brown, Federica Carpico, Tony Cimarosa","Plot":"Symphony in Blood Red is an Italian 'giallo', a horror film inspired by the work of Dario Argento. It is the first feature movie directed by Luigi Pastore, and in collaboration with ...","Language":"Italian","Country":"Italy","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"3.9","imdbVotes":"78","imdbID":"tt2091423","Type":"movie","Response":"True"}
{ json: '{"Title":"Symphony in Blood Red","Year":"2010","Rated":"N/A","Released":"21 Oct 2010","Runtime":"80 min","Genre":"Horror","Director":"Luigi Pastore","Writer":"Luigi Pastore (screenplay), Luigi Pastore (story), Antonio Tentori (screenplay)","Actors":"Sharon Alessandri, Nikol Brown, Federica Carpico, Tony Cimarosa","Plot":"Symphony in Blood Red is an Italian \'giallo\', a horror film inspired by the work of Dario Argento. It is the \u001ffirst feature movie directed by Luigi Pastore, and in collaboration with ...","Language":"Italian","Country":"Italy","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"3.9","imdbVotes":"78","imdbID":"tt2091423","Type":"movie","Response":"True"}',
  errors: [] }
undefined:1
lo', a horror film inspired by the work of Dario Argento. It is the first fea
                                                                    ^
SyntaxError: Unexpected token 
    at Object.parse (native)
    at Request._callback (/omdb/omdbApiTest.js:11:21)
    at Request.self.callback (/omdb/node_modules/request/request.js:197:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/omdb/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/omdb/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

I was hoping this module would be able to fix this. Could such a fix be implemented?

Example code:

```
var request = require('request');
durableJsonLint = require('durable-json-lint');

request({
    url: "http://www.omdbapi.com/?i=tt2091423&plot=small&r=json ",
    json:true
}, function(err, response, json){
    if (json && typeof json !== 'object'){
        console.log(json);
        console.log(durableJsonLint(json));
        json = JSON.parse(durableJsonLint(json).json); // each record is sucessfully parsed and output 
        console.log(json.Title);
        console.log(json.Plot);
    }
});
```

**Comment by freethenation** [comment]
Yea... I have a fix... at work so will apply the patch tonight. If ya need it to work right now the following example works:
var request = require('request');durableJsonLint = require('./index.js');
request({    url: "http://www.omdbapi.com/?i=tt2091423&plot=small&r=json ",    json:true}, function(err, response, json){    if (json && typeof json !== 'object'){        console.log(json);        json = json.replace(/[\u0000-\u001f]/g, function(c){ return JSON.stringify(c).slice(1,-1);} );        console.log(durableJsonLint(json));        json = JSON.parse(durableJsonLint(json).json); // each record is sucessfully parsed and output         console.log(json.Title);        console.log(json.Plot);    }}); 


     On Thursday, July 23, 2015 7:53 AM, Jip-Hop <notifications@github.com> wrote:
   

 Hi,I'm using a web-service that returns invalid JSON. While the durable-json-lint module is useful for fixing some errors, it currently doesn't fix unescaped unicode characters in the range of u0000 to u001f.{"Title":"Symphony in Blood Red","Year":"2010","Rated":"N/A","Released":"21 Oct 2010","Runtime":"80 min","Genre":"Horror","Director":"Luigi Pastore","Writer":"Luigi Pastore (screenplay), Luigi Pastore (story), Antonio Tentori (screenplay)","Actors":"Sharon Alessandri, Nikol Brown, Federica Carpico, Tony Cimarosa","Plot":"Symphony in Blood Red is an Italian 'giallo', a horror film inspired by the work of Dario Argento. It is the first feature movie directed by Luigi Pastore, and in collaboration with ...","Language":"Italian","Country":"Italy","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"3.9","imdbVotes":"78","imdbID":"tt2091423","Type":"movie","Response":"True"}
{ json: '{"Title":"Symphony in Blood Red","Year":"2010","Rated":"N/A","Released":"21 Oct 2010","Runtime":"80 min","Genre":"Horror","Director":"Luigi Pastore","Writer":"Luigi Pastore (screenplay), Luigi Pastore (story), Antonio Tentori (screenplay)","Actors":"Sharon Alessandri, Nikol Brown, Federica Carpico, Tony Cimarosa","Plot":"Symphony in Blood Red is an Italian \'giallo\', a horror film inspired by the work of Dario Argento. It is the \u001ffirst feature movie directed by Luigi Pastore, and in collaboration with ...","Language":"Italian","Country":"Italy","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"3.9","imdbVotes":"78","imdbID":"tt2091423","Type":"movie","Response":"True"}',
  errors: [] }
undefined:1
lo', a horror film inspired by the work of Dario Argento. It is the first fea
                                                                    ^
SyntaxError: Unexpected token 
    at Object.parse (native)
    at Request._callback (/omdb/omdbApiTest.js:11:21)
    at Request.self.callback (/omdb/node_modules/request/request.js:197:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/omdb/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/omdb/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
I was hoping this module would be able to fix this. Could such a fix be implemented?Example code:var request = require('request');
durableJsonLint = require('durable-json-lint');

request({
    url: "http://www.omdbapi.com/?i=tt2091423&plot=small&r=json ",
    json:true
}, function(err, response, json){
    if (json && typeof json !== 'object'){
        console.log(json);
        console.log(durableJsonLint(json));
        json = JSON.parse(durableJsonLint(json).json); // each record is sucessfully parsed and output 
        console.log(json.Title);
        console.log(json.Plot);
    }
});

**Comment by richardklafter** [comment]
Yea... I have a fix... at work so will apply the patch tonight. If you need it to work right now the following example works:

``` javascript
var request = require('request');
durableJsonLint = require('./index.js');

request({
    url: "http://www.omdbapi.com/?i=tt2091423&plot=small&r=json ",
    json:true
}, function(err, response, json){
    if (json && typeof json !== 'object'){
        console.log(json);
        json = json.replace(/[\u0000-\u001f]/g, function(c){ return JSON.stringify(c).slice(1,-1);} );
        console.log(durableJsonLint(json));
        json = JSON.parse(durableJsonLint(json).json); // each record is sucessfully parsed and output 
        console.log(json.Title);
        console.log(json.Plot);
    }
});
```

**Comment by Jip-Hop** [comment]
Wow great :) I didn't know you could do that with regex. I looked it up on regex101.com and this is what is says.

```
/[\u0000-\u001f]/g
  [\u0000-\u001f] match a single character present in the list below
    \u0000-\u001f a single character in the range between the following two characters
      \u0000 the literal character u0000 (case sensitive)
      \u001f the literal character u001f (case sensitive)
    g modifier: global. All matches (don't return on first match)
```

So you're looking up the unescaped characters in the range \u0000-\u001f and replace them with a JSON stringified version of that character with double quotes removed (first and last character). Exactly the fix I needed!

Your example code works and fixes the three different cases of malformed JSON returned from the API. 

First case: An escaped single quote in the movie plot (http://www.omdbapi.com/?i= tt0477543&plot=full&r=json)
Second case: Unescaped backslash in the movie title (http://www.omdbapi.com/?i= tt0102445&plot=full&r=json)
The third case: The plot contains an invalid character \u001F (http://www.omdbapi.com/?i=tt2091423&plot=full&r=json)

In my search for a solution I also came across a one line solution to parsing malformed JSON to a JavaScript object as response to this StackOverflow question: http://stackoverflow.com/questions/17961303/why-does-json-parse-choke-on-encoded-characters-in-nodejs The suggested solution is this: `json = new Function( 'return ' + json )();` This is also capable of parsing the above mentioned three cases of malformed JSON but has two downsides to durable-json-lint and your new fix. The first is that durable-json-lint lets the user know what the problem was with the JSON notation. With the `new Function` approach you don't know where the errors were. The second downside is that this opens up the possibility of executing malicious code. Therefore it should be executed in a sandbox. I tried to make a fix around this solution with https://github.com/asvd/jailed but think your solution is a lot better. Just mentioning it for reference.

I'm looking forward to the next version of durable-json-lint with this fix included!

**Comment by freethenation** [comment]
New version on npm that fixes the issue.

**Comment by Jip-Hop** [comment]
Thank you!

**Comment by Jip-Hop** [comment]
I came across two more invalid JSON responses which can't be parsed with durable-json-lint.

The problems ids are:
tt0255309: http://www.omdbapi.com/?i=tt0255309&plot=full&r=json
Here the double quotes in the plot have been escaped twice, e.g.: \"Prithvi \". This occurs 4 times in the plot.

tt2828840: http://www.omdbapi.com/?i=tt2828840&plot=full&r=json
Here the double quote closing the plot has been escaped.

Do you think you're able to automatically correct these issues? Or are these errors too big? I informed the API author but thought these examples may be interesting to improve durable-json-lint.
